In [1]:
import numpy as np
from numpy.linalg import inv, det, matrix_rank
from sklearn.metrics import mean_squared_error, r2_score

In [2]:
x = np.array([1,5,10]).reshape(-1,1)
w = np.array([5,6,1]).reshape(-1,1)
print("x:\n", x)
print("w:\n", w)

y1 = x.T.dot(w)
print("\nDot product: ", y1)

x:
 [[ 1]
 [ 5]
 [10]]
w:
 [[5]
 [6]
 [1]]

Dot product:  [[45]]


In [3]:
x = np.array([1,5,10])
w = np.array([5,6,1])

print("Dot Product x.w: ", x.dot(w))
print("Dot product w.x: ", w.dot(x) )

Dot Product x.w:  45
Dot product w.x:  45


In [4]:
w = np.array([5,6,1])
X = np.array([[1,5,10],
              [1,4,9],
              [1,3,13],
              [1,2,6]
              ])

y = X.dot(w)
print("y: ", y)

y:  [45 38 36 23]


## Linear Regression: Square data matrix

In [5]:
# Linear Regression: Square data matrix
X = np.array([[13, 22, 35],
              [17,13,9],
              [7, 3, 12],
              [1, 31, 1]
              ])

X_bias = np.c_[np.ones((X.shape[0], 1)), X]

y = np.array([22, 34, 45, 67]).reshape(-1,1)

w =np.linalg.inv(X_bias).dot(y)

print("X: \n", X)
print("y: \n", y)

print("\nCalculated w: \n",w)

print("\n ----------------Model Evaluation---------------------")
y_predicred = X_bias.dot(w)

print("Mean Squared Error: %.2f"%mean_squared_error(y, y_predicred))
print("Coefficient of Determination r^2 variance score: %.f"%r2_score(y, y_predicred))

X: 
 [[13 22 35]
 [17 13  9]
 [ 7  3 12]
 [ 1 31  1]]
y: 
 [[22]
 [34]
 [45]
 [67]]

Calculated w: 
 [[63.96483756]
 [-1.49554279]
 [ 0.1703645 ]
 [-0.75059429]]

 ----------------Model Evaluation---------------------
Mean Squared Error: 0.00
Coefficient of Determination r^2 variance score: 1


## Data Matrix X is Non-Square

In [6]:
# Non-Square X: No collinearity

X = np.array([[13, 22, 35],
              [17, 13, 9]
              ])

y = np.array([22, 34]).reshape(-1,1)

print("Rank of X:", matrix_rank(X))

X_bias = np.c_[np.ones((X.shape[0],1)), X]

print("\nRank of X_bias: ", matrix_rank(X_bias))

z = X_bias.T.dot(X_bias)

print("\nRank of z: ", matrix_rank(z))

w = np.linalg.inv(z).dot(X_bias.T).dot(y)
print("\nWeight vector: \n", w)


print("\n ----------------Model Evaluation---------------------")
y_predicred = X_bias.dot(w)

print("Mean Squared Error: %.2f"%mean_squared_error(y, y_predicred))
print("Coefficient of Determination r^2 variance score: %.f"%r2_score(y, y_predicred))


Rank of X: 2

Rank of X_bias:  2

Rank of z:  2

Weight vector: 
 [[ 1.3400000e+02]
 [ 6.2500000e-02]
 [-4.1640625e+00]
 [ 5.9375000e-01]]

 ----------------Model Evaluation---------------------
Mean Squared Error: 2247.60
Coefficient of Determination r^2 variance score: -61


## Non-Square X with Collinearity

In [25]:
X = np.array([[1,2,3,4],
              [7,14,11,12]])

print("Rank of X: ", matrix_rank(X))

Z = X.T.dot(X)
print("Rank of Z:", matrix_rank(Z))
print(Z)
print("Determinant of Z (X^T.X): ", det(Z))

eigenvalues, eigenvectors = np.linalg.eig(Z)
print("\nEigenvalues of Z: \n", eigenvalues)

noOfZeroEigenvalus = 0
for i in eigenvalues:
    if i>0:
        noOfZeroEigenvalus+=0
    else:
        noOfZeroEigenvalus+=1

print("\nNumber of zero/negative eigenvalues: ", noOfZeroEigenvalus)
Z_inv = np.linalg.inv(Z)
print(Z_inv)

Rank of X:  2
Rank of Z: 2
[[ 50 100  80  88]
 [100 200 160 176]
 [ 80 160 130 144]
 [ 88 176 144 160]]
Determinant of Z (X^T.X):  0.0

Eigenvalues of Z: 
 [ 5.36563313e+02  3.43668670e+00 -2.40578862e-14 -1.15269744e-14]

Number of zero/negative eigenvalues:  2


LinAlgError: Singular matrix

## Finding the Singularity Problem of $(X^TX)^{-1}$

In [33]:
X = np.array([[1,2,3,4],
              [7,14,11,12]])

print("Rank of X: ", matrix_rank(X))

Z = X.T.dot(X)
print("Rank of Z:", matrix_rank(Z))
print(Z)
print("Determinant of Z (X^T.X): ", det(Z))

eigenvalues, eigenvectors = np.linalg.eig(Z)
print("\nEigenvalues of Z: \n", eigenvalues)

noOfZeroEigenvalus = 0
for i in eigenvalues:
    if i>0:
        noOfZeroEigenvalus+=0
    else:
        noOfZeroEigenvalus+=1

print("\nNumber of zero/negative eigenvalues: ", noOfZeroEigenvalus)

print("\n-------- Fixing the Singularity of (X^T)X ------------")

diagonal = np.array([[0.001,0,0,0],
                     [0,0.001,0,0],
                     [0,0,0.001,0],
                     [0,0,0,0.001]])

print("\nDiagonal Matrix: \n", diagonal)

print("\nZ + Diagonal Matrix: ")
Z = Z + diagonal
print(Z)

eigenvalues, eigenvectors = np.linalg.eig(Z)
print("\nEigenvalues of (Z + Diagonal: )")
print(eigenvalues)


print("\nDeterminant of Z (X^T.X) after adding the diagonal matrix: ", det(Z))

# Invert X^T.X
Z_inv = np.linalg.inv(Z)
print("\nInverse of X^T.X:")
print(Z_inv)

Rank of X:  2
Rank of Z: 2
[[ 50 100  80  88]
 [100 200 160 176]
 [ 80 160 130 144]
 [ 88 176 144 160]]
Determinant of Z (X^T.X):  0.0

Eigenvalues of Z: 
 [ 5.36563313e+02  3.43668670e+00 -2.40578862e-14 -1.15269744e-14]

Number of zero/negative eigenvalues:  2

-------- Fixing the Singularity of (X^T)X ------------

Diagonal Matrix: 
 [[0.001 0.    0.    0.   ]
 [0.    0.001 0.    0.   ]
 [0.    0.    0.001 0.   ]
 [0.    0.    0.    0.001]]

Z + Diagonal Matrix: 
[[ 50.001 100.     80.     88.   ]
 [100.    200.001 160.    176.   ]
 [ 80.    160.    130.001 144.   ]
 [ 88.    176.    144.    160.001]]

Eigenvalues of (Z + Diagonal: )
[5.36564313e+02+0.0000000e+00j 3.43768670e+00+0.0000000e+00j
 1.00000000e-03+9.3634816e-15j 1.00000000e-03-9.3634816e-15j]

Determinant of Z (X^T.X) after adding the diagonal matrix:  0.0018445400010308195

Inverse of X^T.X:
[[ 806.97084379 -386.05831243  -69.43736646   43.32353863]
 [-386.05831243  227.88337513 -138.87473292   86.64707727]
 [ -69.43736