In [1]:
import numpy as np
from numpy.linalg import inv, det, matrix_rank
from sklearn.metrics import mean_squared_error, r2_score

In [10]:
x = np.array([1,5,10]).reshape(-1,1)
w = np.array([5,6,1]).reshape(-1,1)
print("x:\n", x)
print("w:\n", w)

y1 = x.T.dot(w)
print("\nDot product: ", y1)

x:
 [[ 1]
 [ 5]
 [10]]
w:
 [[5]
 [6]
 [1]]

Dot product:  [[45]]


In [14]:
x = np.array([1,5,10])
w = np.array([5,6,1])

print("Dot Product x.w: ", x.dot(w))
print("Dot product w.x: ", w.dot(x) )

Dot Product x.w:  45
Dot product w.x:  45


In [15]:
w = np.array([5,6,1])
X = np.array([[1,5,10],
              [1,4,9],
              [1,3,13],
              [1,2,6]
              ])

y = X.dot(w)
print("y: ", y)

y:  [45 38 36 23]


## Linear Regression: Square data matrix

In [41]:
# Linear Regression: Square data matrix
X = np.array([[13, 22, 35],
              [17,13,9],
              [7, 3, 12],
              [1, 31, 1]
              ])

X_bias = np.c_[np.ones((X.shape[0], 1)), X]

y = np.array([22, 34, 45, 67]).reshape(-1,1)

w =np.linalg.inv(X_bias).dot(y)

print("X: \n", X)
print("y: \n", y)

print("\nCalculated w: \n",w)

print("\n ----------------Model Evaluation---------------------")
y_predicred = X_bias.dot(w)

print("Mean Squared Error: %.2f"%mean_squared_error(y, y_predicred))
print("Coefficient of Determination r^2 variance score: %.f"%r2_score(y, y_predicred))

X: 
 [[13 22 35]
 [17 13  9]
 [ 7  3 12]
 [ 1 31  1]]
y: 
 [[22]
 [34]
 [45]
 [67]]

Calculated w: 
 [[63.96483756]
 [-1.49554279]
 [ 0.1703645 ]
 [-0.75059429]]

 ----------------Model Evaluation---------------------
Mean Squared Error: 0.00
Coefficient of Determination r^2 variance score: 1


## Data Matrix X is Non-Square

In [53]:
# Non-Square X: No collinearity

X = np.array([[13, 22, 35],
              [17, 13, 9]
              ])

y = np.array([22, 34]).reshape(-1,1)

print("Rank of X:", matrix_rank(X))

X_bias = np.c_[np.ones((X.shape[0],1)), X]

print("\nRank of X_bias: ", matrix_rank(X_bias))

z = X_bias.T.dot(X_bias)

print("\nRank of z: ", matrix_rank(z))

w = np.linalg.inv(z).dot(X_bias.T).dot(y)
print("\nWeight vector: \n", w)


print("\n ----------------Model Evaluation---------------------")
y_predicred = X_bias.dot(w)

print("Mean Squared Error: %.2f"%mean_squared_error(y, y_predicred))
print("Coefficient of Determination r^2 variance score: %.f"%r2_score(y, y_predicred))


Rank of X: 2

Rank of X_bias:  2

Rank of z:  2

Weight vector: 
 [[ 1.3400000e+02]
 [ 6.2500000e-02]
 [-4.1640625e+00]
 [ 5.9375000e-01]]

 ----------------Model Evaluation---------------------
Mean Squared Error: 2247.60
Coefficient of Determination r^2 variance score: -61
